/**
 * One shared description block for every known visual template — which
 * physical/mathematical setup it matches, and its exact parameter shape.
 * Used by both the visual-planning prompt (AI picks templates
 * automatically) and the lesson-patch prompt (AI picks a template on
 * request via chat), so a template's guidance never drifts out of sync
 * between the two paths. See VISUAL_TEMPLATE_GUIDE.md: adding a template
 * means updating this file too.
 */
export const TEMPLATE_DESCRIPTIONS = `- "radial-charged-sphere" (type: "scientific-diagram"): spherically symmetric electrostatics — a uniformly charged solid sphere, or a thin charged spherical shell. Use for point-charge-like or spherical Gaussian-surface problems (field falls off as 1/r² outside). NOT for wires or planes. Parameters: { sphereType?: "solid-insulator"|"shell", chargeSign?: "positive"|"negative", showGaussianSurface?: boolean, showFieldVectors?: boolean, showIntegralPath?: boolean, showPotentialPlot?: boolean, initialObservationRadiusRatio?: number (0-2) }.

- "long-charged-wire" (type: "scientific-diagram"): cylindrical symmetry — a long/infinite straight charged wire or cylinder (solid insulating rod, or hollow conducting shell). Use for line-charge or cylindrical-Gaussian-surface problems where the field falls off as 1/r, not 1/r². Parameters: { wireType?: "solid-insulator"|"conducting-shell", chargeSign?: "positive"|"negative", showGaussianSurface?: boolean, showFieldVectors?: boolean, showPotentialPlot?: boolean, initialObservationRadiusRatio?: number (0-2) }.

- "infinite-plane" (type: "scientific-diagram"): planar symmetry — a single infinite charged sheet, or a parallel-plate capacitor. Use when the field magnitude is constant with distance (single-plane) or confined between two plates (parallel-plates). Parameters: { configuration?: "single-plane"|"parallel-plates", chargeSign?: "positive"|"negative", showFieldVectors?: boolean, showPotentialPlot?: boolean, initialObservationPositionRatio?: number (-2 to 2) }.

- "electric-dipole" (type: "scientific-diagram"): two opposite point charges (+q, -q) forming a dipole. Has two modes — pick the one that matches what the section is actually explaining: mode "far-field-comparison" shows the field at a far axial point vs. a far equatorial point (magnitude and direction compared — axial is twice the equatorial magnitude and points the opposite way relative to p; matches "approximate field of a dipole at axial/equatorial points" content); mode "torque-in-field" shows the dipole rotating in a uniform external field with its torque and potential energy (matches "torque on a dipole in a uniform field" content). Parameters: { mode?: "far-field-comparison"|"torque-in-field", showFieldLines?: boolean, showExternalField?: boolean, showTorqueVector?: boolean, showPotentialEnergyPlot?: boolean, initialAngleDegrees?: number (0-180, angle between dipole moment and external field — torque-in-field mode only), initialDistanceRatio?: number (1.5-5, observation distance / charge separation — far-field-comparison mode only) }.

- "dielectric-polarization" (type: "scientific-diagram"): molecular polarization inside a dielectric material placed in an external electric field. Use when a section discusses induced dipoles, permanent dipoles reorienting, bound surface charge, polarization field, reduced net field in a dielectric, dielectric constant, or why polarization opposes the field from fixed free charge. Do NOT use the point-charge "electric-dipole" template for dielectric material polarization unless the section is specifically about one isolated dipole's torque or far field. Parameters: { materialKind?: "induced"|"permanent"|"mixed", showExternalField?: boolean, showOpposingField?: boolean, showBoundSurfaceCharge?: boolean, initialAlignment?: number (0-1) }.

- "generated-illustration" (type: "generated-illustration"): a custom AI-generated instructional image. Use when the section needs a visual explanation but none of the coded templates is specific enough, when the user explicitly asks for an image/picture/illustration, or when two sections share the same physical object but need different conceptual states (for example, dielectric inserted after battery disconnection vs while the battery remains connected). Prefer this over reusing an unrelated or identical coded simulation. Parameters: { imagePrompt: string (20+ chars, precise prompt for the image model), caption?: string }. Do not include imageDataUrl; the server fills that after generating the image.

- "force-vector-diagram" (type: "scientific-diagram"): free-body / force-vector diagrams — one or more force vectors on an object, optionally with their resultant. Use for mechanics (Newton's laws, statics, free-body diagrams), not electromagnetism. Parameters: { vectors?: [{ id: string, label: string, magnitude: number (0-1), angleDegrees: number (0-360), color?: string }] (at least 1 if provided), coordinateSystem?: "cartesian"|"polar", showResultant?: boolean, allowDragging?: boolean }.

- "particle-container" (type: "simulation"): particles in a container, optionally split by a membrane — diffusion, concentration gradients, osmosis. Use for transport/diffusion concepts, not fields. Parameters: { membranePresent?: boolean, membranePermeable?: boolean, initialConcentrationLeft?: number (0-1), initialConcentrationRight?: number (0-1), particleCount?: number (4-200), animate?: boolean }.

- "process-flow-diagram" (type: "process-flow"): a sequence of labeled stages/steps with directed connections. Use for procedures, algorithms, or multi-step processes — not physical quantities. Parameters: { stages?: [{ id: string, label: string, next: string[] (ids of stages this leads to) }] (at least 1 if provided), animateProgression?: boolean }.

- "coordinate-geometry" (type: "mathematical-plot"): a labeled 2D coordinate-plane plot — points, vectors, and/or curves (only linear, quadratic, or sine — no arbitrary formulas), with optional shaded regions. Use for pure math/graphing content, or as a general-purpose fallback for an equation-heavy section that doesn't match a more specific template (e.g. plot the equation's shape, or the key variables as points/vectors). Parameters: { xRange?: [number, number], yRange?: [number, number], points?: [{x: number, y: number, label?: string}], vectors?: [{fromX: number, fromY: number, toX: number, toY: number, label?: string}], curves?: [{curveType:"linear", slope: number, intercept: number} | {curveType:"quadratic", a: number, b: number, c: number} | {curveType:"sine", amplitude: number, frequency: number, phase?: number}], shadedRegions?: [{curveIndex: number, fromX: number, toX: number}], showGrid?: boolean, xAxisLabel?: string, yAxisLabel?: string }.

- "wave-diagram" (type: "mathematical-plot"): a single traveling or standing sinusoidal wave. Use for oscillations, sound, or light-as-a-wave content. Parameters: { amplitude?: number (0-1), wavelength?: number (0.1-4), initialPhase?: number, propagationDirection?: "left"|"right", waveSpeed?: number (0.1-5), animate?: boolean }.

- "simple-circuit" (type: "scientific-diagram"): a basic series or parallel resistor circuit with a voltage source. Use only for circuit/Ohm's-law content. Parameters: { configuration?: "series"|"parallel", voltageSource?: number (>0), resistors?: [{id: string, label: string, resistanceOhms: number (>0)}] (at least 1 if provided), showCurrentDirection?: boolean, showValues?: boolean }.`;
