import { z } from "zod";

/**
 * One proposed lesson from the outline pass. `sourceText` must be a
 * verbatim excerpt of the original pasted text (never paraphrased or
 * invented) — see bulkImportPlanService.ts, which drops any entry that
 * doesn't actually appear in the original text before this ever reaches
 * the UI. Each entry is later fed into the normal single-lesson pipeline
 * (`generateLessonPlan`) unchanged, so per-lesson quality matches a lesson
 * generated by pasting that excerpt directly.
 */
export const proposedLessonSchema = z.object({
  title: z.string().min(1),
  topic: z.string().optional(),
  sourceText: z.string().min(1),
});

export const bulkImportPlanSchema = z.object({
  lessons: z.array(proposedLessonSchema).min(1),
});

export type ProposedLesson = z.infer<typeof proposedLessonSchema>;
export type BulkImportPlan = z.infer<typeof bulkImportPlanSchema>;
